# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBEzlFujgWtzBAl30aHKpsj0JZ8pFxD8
"""

#!pip install pandas
#!pip install matplotlib
#!pip install sklearn

import pandas as pd
from matplotlib import pyplot as plt

df=pd.read_csv("nasdaq100.csv", sep=';')
df.head()

df=df.drop('Date',axis=1)  #axis=1 for column

plt.scatter(df['Starting (USD)'],df['Ending (USD)'])
plt.xlabel('Starting (USD)')
plt.ylabel('Ending (USD)')
plt.title('Nasdaq100')
plt.show()

from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(df[['Starting (USD)']],df['Ending (USD)'])
x=df[['Starting (USD)']]
x.head()
y=df['Ending (USD)']
y.head()

x.mean()
y.mean()


#linear regression
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

reg.fit(x,y)  #train the model - moved this line up

plt.scatter(x.mean(),y.mean(), color='red')
plt.scatter(df['Starting (USD)'],df['Ending (USD)'])
plt.scatter(df['Starting (USD)'],reg.predict(x))
plt.xlabel('Starting (USD)')
plt.ylabel('Ending (USD)')
plt.title('Nasdaq100')

m_coef=reg.coef_[0]
c_intercept=reg.intercept_

#y=mx+c

a=m_coef*16700 + c_intercept ##in question what is the value of 16700 as x in y
a

plt.plot(x,reg.predict(x),color='red')

reg.predict([[16200]])


#Loss (error) and cost(total error) function of linear regression

Loss=df['Ending (USD)']-reg.predict(x)
Loss

#Cost-MAE, MSE, RMSE

#MSE and MAE
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse=mean_squared_error(df['Ending (USD)'],reg.predict(x))
mse #80411.23397700385  ##Linear comparison with other
mae=mean_absolute_error(df['Ending (USD)'],reg.predict(x))
mae #260.3840017604666
reg.score(x,y)  #0.3577804940272571


plt.scatter(x.mean(),y.mean(), color='red')
plt.scatter(df['Starting (USD)'],df['Ending (USD)'])
plt.scatter(df['Starting (USD)'],reg.predict(x))
plt.xlabel('Starting (USD)')
plt.ylabel('Ending (USD)')
plt.title('Nasdaq100')

from sklearn.metrics import r2_score
r2_score(y, reg.predict(x))  #0.3577804940272571