# -*- coding: utf-8 -*-
"""Machine Learning- Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnrel3acAZfrGaYF1Vj8JhZYsoSdSTgy
"""

##This script is for machine learning for beginner

#improt library
import pandas as pd
#empty data frame
#df=pd.DataFrame()
#df
#df.info()

city=['Dhaka','Khulna','Rajshahi']  #list creation
city

df=pd.DataFrame(city)
df  #converted into data frame (list to data frame)
type(df)
df.shape #row 3 column 1

#row and column name set

df=pd.DataFrame(city, columns=['city in bd'], index=['c1','c2','c3'])
df


##add another column

city2=['Wyoming','NYC', 'Nevada']
df2=pd.DataFrame(zip(city,city2),columns=['bd','usa'])
df2

#list can be 2 dimensional or more

city3=[['Dhaka','Khulna'],['Wyoming','NYC', 'Nevada']]
df3=pd.DataFrame(city3, columns=['ci1','ci2','ci3'], index=['bd','usa'])
df3

#importing excel file
df6=pd.read_csv('Screen Time Data.csv')
df6.head()
df6.values
df6.columns
df6.shape
df6[['Date','Week Day']].head()

df6['Social Networking'].sort_values()   ##sort ascending
df6['Social Networking'].sort_values(ascending=False)  ##sort descending

#statistical analysis

df6.describe()

#correlation

df6.corr(numeric_only=True)

#heatmap

import seaborn as sns
sns.heatmap(df6.corr(numeric_only=True), annot=True)


#subsetting rows
df6[df6['Social Networking']>50]

#or sign

df6[(df6['Social Networking']>50) | (df6['Week Day'] == 'Wednesday')]

#subsetting using is in

df6[df6['Week Day'].isin(['Saturday','Sunday'])]